version: "3.8"

services:
  main:
    image: ubuntu:22.04
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  secondary:
    image: ubuntu:22.04
    volumes:
      - ../..:/workspaces:cached
    post_start:
      - command: echo '[SECONDARY] Container working_dir:' >> /workspaces/container.log && pwd >> /workspaces/container.log
        user: root
    command: sleep infinity
