version: "3.8"

services:
  main:
    image: ubuntu:22.04
    volumes:
      - ../..:/workspaces:cached

  secondary:
    image: ubuntu:22.04
    volumes:
      - ../..:/workspaces:cached
    command: |
      bash -c "
        echo '[SECONDARY] Container working_dir: $(pwd)' >> /workspaces/container.log
        while true; do sleep 3600; done
      "
