version: "3.8"

services:
  main:
    image: ubuntu:22.04
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces
    command: sleep infinity

  secondary:
    image: ubuntu:22.04
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces
    command: |
      bash -c "
        pwd
        echo 'Secondary container started'
        while true; do 
          sleep 3600
        done
      "
